name = "FirmaPrima"
author = "P1x3l101"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "73d9e5bb961555df45eb3f57f93e3f4d16b5bcaafbae10564e207bdbab3e01b1"

[versions]
forge = "47.4.10"
lwjgl3 = "3.3.1"
minecraft = "1.20.1"
unsup = "1.1.5"
