name = "FirmaPrima"
author = "P1x3l101"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89a65aeeef2eeb11a4988b998057ffeefcdd4782a79b0667fa8bdd42e6ec6816"

[versions]
forge = "47.4.10"
lwjgl3 = "3.3.1"
minecraft = "1.20.1"
unsup = "1.1.5"
