name = "FirmaPrima"
author = "P1x3l101"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61ff8e08cc1913aa4e6c79427b0a193dee27c20f6c047d43a826ffb5b21a634f"

[versions]
forge = "47.4.10"
lwjgl3 = "3.3.1"
minecraft = "1.20.1"
unsup = "1.1.5"
