name = "FirmaPrima"
author = "P1x3l101"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5016e7b79b770b5200b50ed97322536dda78758a4e23d7d49c61dfcebdd4018e"

[versions]
forge = "47.4.10"
lwjgl3 = "3.3.1"
minecraft = "1.20.1"
unsup = "1.1.5"
