name = "FirmaPrima"
author = "P1x3l101"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7e8cfd6a0b553c5345f077be5c6d516b2685976de86a5764a32e56161a0ed5c"

[versions]
forge = "47.4.10"
lwjgl3 = "3.3.1"
minecraft = "1.20.1"
unsup = "1.1.5"
