maxMinds = 64
mediaDiscount = 0.75
playerSleepSpell = true
earlyDamageTriggers = false
discountBlacklist = ["hexal:wisp/summon/projectile", "hexal:wisp/summon/ticking", "hexical:conjure_gummy", "hexical:charm", "hexical:recharge_lamp", "lapisworks:imbue_lap", "yaha:time_bomb"]
