name: Packwiz
on:
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_packwiz_packs:
    runs-on: ubuntu-24.04
    steps:
      - run: sudo GOBIN=/usr/local/bin go install github.com/packwiz/packwiz@latest
      - uses: ConorMacBride/install-package@v1
        with:
          apt: minisign
  
      - uses: actions/checkout@v4
        with:
          ref: main
          path: main
          lfs: true
      - name: build main pack
        working-directory: main
        run: |
          bash -c "rm -rf $(cat .packwizignore | xargs)"
          echo "hash-format = \"sha256\"" > index.toml
          /usr/local/bin/packwiz refresh --build
      - name: Get key
        env:
          SIGNINGKEY_BASE64: ${{ secrets.SIGNINGKEY_BASE64 }}
        run: |
          mkdir -p ~/.minisign
          echo "$SIGNINGKEY_BASE64" | base64 --decode > ~/.minisign/minisign.key
      - name: Sign pack files
        run:
          echo "" | minisign -Slm main/pack.toml -x main/unsup.sig;
          echo "" | minisign -Slm main/unsup.ini -x main/unsup.ini.sig
      - name: Remove key
        run:
          rm ~/.minisign/minisign.key
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .

          
  deploy:
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build_packwiz_packs
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
